# Generated by Django 5.1.6 on 2025-03-27 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('twitch_channel', models.CharField(max_length=200)),
            ],
        ),
    ]
