# Generated by Django 5.1.6 on 2025-03-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0002_chatbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='gemini_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='simplecommands',
            name='chatbot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatengine.chatbot'),
            preserve_default=False,
        ),
    ]
