# Generated by Django 5.1.6 on 2025-03-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0003_chatbot_gemini_api_key_simplecommands_chatbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='access_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='token_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='twitch_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
