# Generated by Django 5.1.6 on 2025-03-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0004_alter_chatbot_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='rephrase_promt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
