# Generated by Django 5.1.6 on 2025-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0005_chatbot_rephrase_promt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='twitch_prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
