# Generated by Django 5.1.6 on 2025-03-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0006_chatbot_twitch_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='twitch_prefix',
            field=models.CharField(blank=True, default='!', max_length=20, null=True),
        ),
    ]
