# Generated by Django 5.1.6 on 2025-03-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0007_alter_chatbot_twitch_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='generic_promt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
