# Generated by Django 5.1.6 on 2025-04-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0008_chatbot_generic_promt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='generic_promt',
            new_name='generic_prompt',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='rephrase_promt',
            new_name='rephrase_prompt',
        ),
    ]
