# Generated by Django 5.1.6 on 2025-04-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0009_rename_generic_promt_chatbot_generic_prompt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='gemini_api_key',
            new_name='openai_api_key',
        ),
    ]
