# Generated by Django 5.1.6 on 2025-04-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0010_rename_gemini_api_key_chatbot_openai_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('callname', models.CharField(blank=True, max_length=200, null=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatengine.chatbot')),
            ],
            options={
                'unique_together': {('chatbot', 'platform', 'username')},
            },
        ),
    ]
