# Generated by Django 5.1.6 on 2025-04-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatengine', '0011_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='current_score',
            field=models.IntegerField(default=1000),
        ),
    ]
